#! /usr/bin/bash

# This node's IPv4 address
#DEFAULT_IPV4=<DEFAULT_IPV4>

# The Kubernetes master IP
KUBERNETES_MASTER=172.18.18.101

# IP and port of etcd instance used by Calico
ETCD_AUTHORITY=172.18.18.101:2379

# URL to access the Kubernetes apiserver
KUBE_API_ROOT=http://172.18.18.101:8080/api/v1/

# Enable Calcio IPAM
CALICO_IPAM=true
